version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER:   postgres
      POSTGRES_PASSWORD: marketplace_password
      POSTGRES_DB:     marketplace_db
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db
    restart: always
    ports:
      - "5000:5000"
    environment:
      DB_HOST:     db
      DB_USER:     postgres
      DB_PASSWORD: marketplace_password
      DB_NAME:     marketplace_db
      DB_PORT:     5432
      JWT_KEY:     your_jwt_secret_here
    volumes:
      - ./backend/uploads:/app/uploads

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    depends_on:
      - backend
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=/api

volumes:
  db_data:
