version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    env_file:
      - ./frontend/.env    

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${BACKEND_IMAGE}
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    restart: always
    volumes:
      - ./backend/uploads:/app/uploads

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
